[package]
name = "error-code"
version = "0.1.0"
edition = "2021"
authors = ["Ethan <liu.zy.ethan@gmail.com>"]
license = "MIT or Apache-2.0"

[dependencies]
error-code-derive = { workspace = true }

[dev-dependencies]
thiserror = { workspace = true }
http = { workspace = true }
